# api/docker/Dockerfile.prod
# Build Stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY api/go.mod api/go.sum ./
RUN go mod download

COPY api/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/server

# Run Stage
FROM alpine:latest

# Устанавливаем curl и gnupg для верификации и установки Doppler
RUN apk --no-cache add curl gnupg

# Скачиваем и устанавливаем Doppler CLI
RUN curl -Ls --tlsv1.2 --proto "=https" --retry 3 "https://cli.doppler.com/install.sh" | sh

WORKDIR /root/

# Копируем скомпилированный бинарник
COPY --from=builder /app/main .

# Запускаем бинарник через Doppler, чтобы подтянуть секреты окружения
CMD ["doppler", "run", "--", "./main"]
