# api/docker/Dockerfile.dev

# Use the Go base image
FROM golang:1.25-alpine

WORKDIR /app

# Install Air for hot reload
RUN go install github.com/air-verse/air@latest

# Copy go.mod and go.sum so we can cache go mod downloads
COPY api/go.mod api/go.sum ./

RUN go mod download

# Don't copy the rest of the code here. 
# We'll rely on volume mounting for local dev.

# Expose port
EXPOSE 8164

# Command to run Air
CMD ["air", "-c", ".air.toml"]
